FROM eclipse-temurin:17-jre-jammy

WORKDIR /app

COPY services/task-service/target/task-service-0.0.1-SNAPSHOT.jar /app/app.jar

EXPOSE 8084

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS:-} -jar /app/app.jar"]
